### PR TITLE
set idle timeout for io client

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
i saw this change was reverted, but when i looked through the code it passes the client settings in the request `requestInternalGeneric` of rhttp_client so it seems logical to me that this change should work (correct me if i am wrong, i dont have that much knowledge with rust)

related to https://github.com/Tienisto/rhttp/issues/27

### CODE REVIEW

**Comment by Tienisto** [comment]
copyWith is creating a new instance, so this line is a noop

**Comment by Tienisto** [comment]
I've changed it into a noop, not throwing an exception anymore

**Comment by abdelaziz-mahdy** [comment]
> copyWith is creating a new instance, so this line is a noop

cant we just convert the type of the settings variable to non final and update it? that will make the set idle timeout work instead of being ignored? what do you think

**Comment by Tienisto** [comment]
The `settings` is immutable because it is stored in Rust. If we make it mutable, then it would be a lot more complicated to keep everything in sync. Also, immutability is clean while Dart's mutable design is quick and dirty.

There is a workaround to make it work regardless.
We can store a mutable `timeout` class variable specifically for `IoCompatibleClient` and override the `timeout` for each request.
Such one-time override is currently not implemented though.

**Pull request closed without merging**
