### PR TITLE
Fix SocketAddr port error issue

### PR DESCRIPTION
**Pull request by nkxingxh**
description: https://github.com/Tienisto/rhttp/issues/39#issuecomment-2508899107

### CODE REVIEW

**Comment by Tienisto** [comment]
Thanks. I wonder why the port number is needed in the first place. I could not find any examples for this in reqwest.

**Comment by nkxingxh** [comment]
I just tested `DUMMY_PORT` with 0 and it works fine and without specifying a port.

I think it would be possible to add the feature of specifying the port, not only to allow custom parsing, but also to be able to change the port

**Comment by Tienisto** [comment]
Yes, we can make the port number as an optional argument (preferably a named optional argument)

**Comment by Tienisto** [comment]
Thanks for your investigation. I've added the fix in 2b0e106e0939e453bc5273c96c82250d9f7e9491

**Comment by nkxingxh** [comment]
extremely grateful

**Pull request closed without merging**
